on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Tag is pushed
    runs-on: ubuntu-latest
    steps:
      - name: Run Benchmark
        run: |
          echo "Run Benchmark"
          curl \
            -X POST \
            -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" https://api.github.com/repos/akundev/gh_actions_receiver/actions/workflows/benchmark.yaml/dispatches \
            --data '{"ref": "main", "inputs": "my_tab" }'
