on:
  push:
    branches:
      - "main"
  create:
    tags:
      - "**"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              const result = await github.rest.actions.createWorkflowDispatch({
                owner: 'akundev',
                repo: 'gh_actions_receiver',
                workflow_id: 'benchmark.yaml',
                ref: 'main',
                inputs: {
                  tag_number: ${{ steps.extract_branch.outputs.branch }}
                },
              })
                console.log(result);
              } catch(error) {
                console.error(error);
                core.setFailed(error);
              }